"""
Untethered Core: Runtime State, Initialization, and Network Management
"""
import io
import json
import os
import select
import socket
import sys
import time

try:
    import machine
    import network
except ImportError:
    machine = None
    network = None

try:
    import _thread
except ImportError:
    _thread = None

try:
    import uhashlib as hashlib
    import ubinascii as binascii
except ImportError:
    import hashlib
    import binascii

try:
    import urequests
except ImportError:
    urequests = None

# Global runtime state
_initialized = False
_device_status = "INITIALIZING"
_last_error = None
_device_name = "pico-w"
_device_group = None  # e.g. "radar": which firmware this board runs (see _is_targeted)
_version_file = "version.json"
_manifest_url = None
_secret_key = None
_telnet_port = 23
_telnet_password = None
_beacon_port = 8266
_beacon_interval = 5
_active_telnet_stream = None
_wdt = None
_wifi_ssid = None
_wifi_password = None
_allow_boot_update = False
_allow_unsigned_push = False
_http_timeout = 10  # seconds; a vanished host must never hang the Core 1 daemon

# CYW43 power-management modes, used when the port doesn't expose network.WLAN.PM_NONE /
# PM_PERFORMANCE (ESP32 does, with different values)
_PM_NONE = 0xa11140
_PM_PERFORMANCE = 0xa11142


def get_ip():
    """Returns currently assigned IP address string."""
    try:
        wlan = network.WLAN(network.STA_IF)
        return wlan.ifconfig()[0]
    except Exception:
        return "0.0.0.0"


def _set_low_latency(enabled):
    """Disables Wi-Fi power-save sleep while a Telnet session is open (zero keystroke lag)."""
    try:
        wlan = network.WLAN(network.STA_IF)
        if enabled:
            wlan.config(pm=getattr(network.WLAN, "PM_NONE", _PM_NONE))
        else:
            wlan.config(pm=getattr(network.WLAN, "PM_PERFORMANCE", _PM_PERFORMANCE))
    except Exception:
        pass


def _reconnect_wifi():
    """
    Called periodically by the Core 1 daemon. Returns True when the link is up, otherwise
    starts a non-blocking reconnect so a router outage never leaves the board offline for good.
    """
    try:
        wlan = network.WLAN(network.STA_IF)
        if wlan.isconnected():
            return True
        if not _wifi_ssid:
            return False
        if wlan.status() == getattr(network, "STAT_CONNECTING", 1):
            return False  # Previous attempt still in progress
        print("[Untethered] Wi-Fi link down. Reconnecting...")
        wlan.active(True)
        try:
            _wifi_connect(wlan, _wifi_ssid, _wifi_password)
        except OSError:
            # ESP32: the driver's own auto-reconnect still owns the connection, so connect()
            # raises "Wifi Internal State Error". Reset it and start a fresh attempt.
            wlan.disconnect()
            _wifi_connect(wlan, _wifi_ssid, _wifi_password)
    except Exception as e:
        print(f"[Untethered] Wi-Fi reconnect error: {e}")
    return False


def _wifi_connect(wlan, ssid, password):
    """Joins a WPA network, or an open one when no password is configured."""
    if password:
        wlan.connect(ssid, password)
    else:
        wlan.connect(ssid)


def provision(ssid, password, name="pico-w", country="DE", secret_key=None, boot=True, auto_start=True,
              manifest_url=None, telnet_password=None, group=None):
    """
    Provisions a fresh board with Wi-Fi credentials and bootstrap scripts.
    Generates config.py, boot.py, and starts Untethered on Core 1.
    manifest_url is only needed without secret_key, or for scheduled checks: signed boards follow the
    URL in update notifications. It is where tools/deploy.py serves updates,
    e.g. "http://192.168.1.50:8000/manifest.json".
    """
    # repr() produces valid, escaped Python literals even for quotes/backslashes in passwords
    config_lines = [
        "# Generated by untethered.provision()",
        "WIFI_SSID = " + repr(ssid),
        "WIFI_PASSWORD = " + repr(password),
        "WIFI_COUNTRY = " + repr(country),
        "DEVICE_NAME = " + repr(name),
    ]
    if secret_key:
        config_lines.append("OTA_SECRET_KEY = " + repr(secret_key))
    if manifest_url:
        config_lines.append("OTA_MANIFEST_URL = " + repr(manifest_url))
    if telnet_password:
        config_lines.append("TELNET_PASSWORD = " + repr(telnet_password))
    if group:
        config_lines.append("DEVICE_GROUP = " + repr(group))

    with open("config.py", "w") as f:
        f.write("\n".join(config_lines) + "\n")
    print(f"[Untethered] Written config.py for '{name}'.")

    if boot:
        with open("boot.py", "w") as f:
            f.write("# Untethered Network Bootloader\nimport untethered\nuntethered.start()\n")
        print("[Untethered] Written boot.py (syntax-error immunity bootloader).")

    if auto_start:
        print("[Untethered] Board provisioned. Starting Untethered runtime...")
        start(ssid=ssid, password=password, name=name, secret_key=secret_key, country=country,
              manifest_url=manifest_url, telnet_password=telnet_password, group=group)


def _load_config():
    """Imports config.py without letting a broken file take the board offline."""
    try:
        import config
        return config
    except ImportError:
        return None
    except Exception as e:
        print(f"[Untethered] WARNING: config.py failed to load ({e}). Using defaults.")
        return None


def start(
    ssid=None,
    password=None,
    name=None,
    manifest_url=None,
    secret_key=None,
    telnet=None,
    telnet_port=None,
    telnet_password=None,
    beacon_port=None,
    beacon_interval=None,
    ota_interval=None,
    watchdog_ms=None,
    country=None,
    allow_boot_update=None,
    allow_unsigned_push=None,
    group=None,
):
    """
    Initializes WiFi, remote REPL, and background OTA listeners.
    Spawns background services on the RP2040 second core via _thread.
    Arguments that are omitted (None) fall back to config.py, then to built-in defaults.
    """
    global _initialized, _device_name, _device_group, _manifest_url, _secret_key, _telnet_port, _telnet_password
    global _beacon_port, _beacon_interval, _wdt, _device_status
    global _wifi_ssid, _wifi_password, _allow_boot_update, _allow_unsigned_push

    if _initialized:
        return
    _initialized = True

    config = _load_config()

    def cfg(value, key, default):
        if value is not None:
            return value
        return getattr(config, key, default) if config else default

    ssid = cfg(ssid, "WIFI_SSID", None)
    password = cfg(password, "WIFI_PASSWORD", None)
    country = cfg(country, "WIFI_COUNTRY", "DE")
    telnet = cfg(telnet, "ENABLE_TELNET", True)
    ota_interval = cfg(ota_interval, "OTA_CHECK_INTERVAL", 0)
    watchdog_ms = cfg(watchdog_ms, "WATCHDOG_TIMEOUT_MS", 0)

    _device_name = cfg(name, "DEVICE_NAME", "pico-w")
    _device_group = cfg(group, "DEVICE_GROUP", None)
    _manifest_url = cfg(manifest_url, "OTA_MANIFEST_URL", None)
    _secret_key = cfg(secret_key, "OTA_SECRET_KEY", None)
    _telnet_port = cfg(telnet_port, "TELNET_PORT", 23)
    _telnet_password = cfg(telnet_password, "TELNET_PASSWORD", None)
    _beacon_port = cfg(beacon_port, "BEACON_PORT", 8266)
    _beacon_interval = cfg(beacon_interval, "BEACON_INTERVAL", 5)
    _allow_boot_update = cfg(allow_boot_update, "OTA_ALLOW_BOOT_UPDATE", False)
    _allow_unsigned_push = cfg(allow_unsigned_push, "OTA_ALLOW_UNSIGNED_PUSH", False)
    _wifi_ssid = ssid
    _wifi_password = password

    # Finish an update that lost power mid-commit before anything else runs
    _resume_pending_update()

    if not _secret_key:
        print("[Untethered] WARNING: No OTA_SECRET_KEY set. Updates are unsigned and remote wipe is disabled.")
        if _allow_unsigned_push and not _manifest_url:
            print("[Untethered] WARNING: OTA_ALLOW_UNSIGNED_PUSH is on. Anyone on the network can install code.")
    if telnet and not _telnet_password:
        if _secret_key:
            # A REPL can read config.OTA_SECRET_KEY, and with it sign updates for every board
            print("[Untethered] WARNING: Telnet REPL disabled: OTA_SECRET_KEY is set but TELNET_PASSWORD "
                  "is not, so an open REPL would expose the update key. Set TELNET_PASSWORD to enable it.")
            telnet = False
        else:
            print("[Untethered] WARNING: Telnet REPL has no password. Anyone on the network gets a Python shell.")

    # Set country code for regulatory compliance (network.country on current ports, rp2.country on old Pico W builds)
    try:
        network.country(country)
    except Exception:
        try:
            import rp2
            rp2.country(country)
        except Exception:
            pass

    # Connect WiFi
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)

    if ssid and not wlan.isconnected():
        print(f"[Untethered] Connecting to WiFi '{ssid}'...")
        _wifi_connect(wlan, ssid, password)
        timeout = 40  # 20s: joining can take a while right after power-up
        while not wlan.isconnected() and timeout > 0:
            time.sleep_ms(500)
            timeout -= 1
            print(".", end="")
        print()

    if wlan.isconnected():
        print(f"[Untethered] Connected! Device: {_device_name} | IP: {get_ip()}")
        try:
            led = machine.Pin("LED", machine.Pin.OUT)
            led.on()
        except Exception:
            pass
    else:
        print("[Untethered] WiFi connection failed or not configured. Will keep retrying in the background.")

    if watchdog_ms > 0:
        # The watchdog is fed by the Core 1 network daemon. It recovers a hung daemon or a
        # stalled update; it does NOT detect a hung user application on Core 0.
        try:
            _wdt = machine.WDT(timeout=watchdog_ms)
            print(f"[Untethered] Hardware watchdog enabled ({watchdog_ms}ms)")
        except Exception as e:
            print(f"[Untethered] Could not start WDT: {e}")

    # Launch daemon in background thread on Core 1
    if _thread:
        # Everything that prints at startup runs here, before the daemon exists (see _open_telnet_server)
        telnet_sock = _open_telnet_server(telnet)
        print("[Untethered] Starting background services on Core 1...")
        _thread.start_new_thread(_background_daemon, (ota_interval, telnet_sock))
    else:
        print("[Untethered] Warning: _thread unavailable. Background daemon not started.")

    _device_status = _initial_status()


def _initial_status():
    """STANDBY after an app wipe (which reboots, so the status must come from flash), else RUNNING."""
    try:
        with open(_version_file, "r") as f:
            if json.load(f).get("components", {}).get("app") == "":
                return "STANDBY"
    except Exception:
        pass
    return "RUNNING"
